apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: demo-events
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000
